/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.mtangular.ui.SpringMxBootApp;

import static org.junit.Assert.*;

public class SpringMxBootAppTest {
    public void testSomeLibraryMethod() {
   /*     SpringMxBootApp classUnderTest = new SpringMxBootApp();
        assertTrue(true);
   */ }
}
