package com.mtangular.ui;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Import;
import org.springframework.context.annotation.PropertySource;

import com.mtangular.ui.core.BaseConfig;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@SpringBootApplication
//@Import(value=BaseConfig.class) (exclude=HibernateJpaAutoConfiguration.class)
@EntityScan(basePackages="com.mtrack.murupakkam.model") 
@PropertySource({"classpath:application.properties"})
public class SpringMxBootApp {
	
	public static void main(String[] args) {
		SpringApplication.run(SpringMxBootApp.class, args);
	}
	
	
}
